version: '3.7'

services:
  zipkin:
    image: openzipkin/zipkin:2.23
    container_name: sleuth-zipkin
    restart: unless-stopped
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=elasticsearch
      # Point the zipkin at the storage backend
      - ES_HOSTS=elasticsearch
      # Uncomment to see requests to and from elasticsearch
      - ES_HTTP_LOGGING=BODY
    networks:
      - tracing
    depends_on:
      - elasticsearch
    # Uncomment to enable debug logging
    # command: --logging.level.zipkin2=DEBUG

  dependencies:
    image: ghcr.io/openzipkin/zipkin-dependencies:2.6.4
    container_name: sleuth-elastic-dependencies
    entrypoint: crond -f
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch
    networks:
      - tracing
    depends_on:
      - elasticsearch

  elasticsearch:
    image: bitnami/elasticsearch:7.17.4
    container_name: sleuth-elasticsearch
    # Uncomment to expose the storage port for testing
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - tracing
    volumes:
      - elastic_data:/bitnami/elasticsearch/data

  oracle:
    image: oracledb:19.3.0-ee
    container_name: sleuth-zipkin-oracledb-ee
    restart: unless-stopped
    #Two ports are exposed: 1521 (Oracle Listener), 5500 (OEM Express).
    ports:
      - "1521:1521"
      - "5500:5500"
    networks:
      - tracing
    volumes:
      # The data volume to use for the database.
      # Has to be writable by the Unix "oracle" (uid: 54321) user inside the container!
      # If omitted the database will not be persisted over container recreation.
      - oracle_data:/opt/oracle/oradata
      # Optional: A volume with custom scripts to be run after database startup.
      # - /opt/oracle/scripts/startup
      # Optional: A volume with custom scripts to be run after database setup.
      - ./setup:/opt/oracle/scripts/setup
    environment:
      # The Oracle Database SID that should be used (default: ORCLCDB).
      ORACLE_SID: ORCLCDB
      # The Oracle Database PDB name that should be used (default: ORCLPDB1).
      ORACLE_PDB: ORCLPDB1
      # The Oracle Database SYS, SYSTEM and PDB_ADMIN password (default: auto generated).
      ORACLE_PWD: 5m0J9FtPEhs=1
      # The total memory in MB that should be used for all SGA components (optional).
      # INIT_SGA_SIZE: "0"
      # The target aggregate PGA memory in MB that should be used for all server processes attached to the instance (optional).
      # INIT_PGA_SIZE: "0"
      # The Oracle Database Edition (enterprise/standard).
      # ORACLE_EDITION: "0"
      # The character set to use when creating the database (default: AL32UTF8).
      # ORACLE_CHARACTERSET: "0"
      # To enable archive log mode when creating the database (default: false).
      # ENABLE_ARCHIVELOG: "0"

  rabbitmq:
    image: rabbitmq:3.9.15-management
    container_name: sleuth-zipkin-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - tracing

  jaeger:
    image: jaegertracing/all-in-one:1.33.0
    container_name: sleuth-zipkin-jaeger
    restart: unless-stopped
    volumes:
      - jaeger_data:/tmp
    ports:
      # configs
      - "5778:5778"
      # frontend
      - "16686:16686"
      # zipkin compatible
      - "9422:9411"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    networks:
      - tracing

volumes:
  oracle_data:
    # external: true // Specify if you wish to create yourself
  jaeger_data:
    # external: true // Specify if you wish to create yourself
  elastic_data:
    # external: true // Specify if you wish to create yourself

networks:
  tracing:
    driver: 'bridge'